name: personal_portfolio_website
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.0
  line_icons: ^2.0.3
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.4
  flutter_markdown: ^0.6.18+3
  # http: ^1.2.0
  flutter_html: ^3.0.0-beta.2
  flutter_inset_box_shadow: ^1.0.8
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  rive: ^0.13.4
  http: ^1.2.0
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  flutter_staggered_grid_view: ^0.7.0
  # rive: ^0.13.7

dependency_overrides:
  web: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^4.0.0
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/projects_logo_cropped.png
    - assets/images/person_under_tree_cropped_side.png
    - assets/images/Experience_1.jpg
    - assets/images/personality_1.svg
    - assets/images/github_logo.png
    - assets/images/discord_logo.png
    - assets/images/gmail_logo.png
    - assets/images/linkedin_logo.png
    - assets/images/twitter_logo.png
    - assets/animations/
  # fonts:
  #    - family: FuturaNow
  #      fonts:
  #        - asset: assets\fonts\futura_now\FuturaNowHeadline.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineBlack.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineBlackItalic.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineBold.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineBoldItalic.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineExtraBlack.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineExtraBlackItalic.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineExtraBold.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineExtraBoldItalic.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineExtraLight.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineExtraLightItalic.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineItalic.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineLight.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineLightItalic.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineMedium.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineMediumItalic.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineThin.ttf
  #        - asset: assets\fonts\futura_now\FuturaNowHeadlineThinItalic.ttf







         


  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
